// Mocks generated by Mockito 5.4.6 from annotations
// in monolog/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:monolog/models/entry.dart' as _i3;
import 'package:monolog/models/entry_attachment.dart' as _i4;
import 'package:monolog/models/entry_with_attachment.dart' as _i9;
import 'package:monolog/models/link_preview.dart' as _i5;
import 'package:monolog/models/search_result.dart' as _i10;
import 'package:monolog/models/topic.dart' as _i2;
import 'package:monolog/models/topic_with_stats.dart' as _i8;
import 'package:monolog/services/database_service.dart' as _i6;
import 'package:monolog/services/file_service.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTopic_0 extends _i1.SmartFake implements _i2.Topic {
  _FakeTopic_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEntry_1 extends _i1.SmartFake implements _i3.Entry {
  _FakeEntry_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEntryAttachment_2 extends _i1.SmartFake
    implements _i4.EntryAttachment {
  _FakeEntryAttachment_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinkPreview_3 extends _i1.SmartFake implements _i5.LinkPreview {
  _FakeLinkPreview_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i6.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.Topic> insertTopic(String? title) =>
      (super.noSuchMethod(
            Invocation.method(#insertTopic, [title]),
            returnValue: _i7.Future<_i2.Topic>.value(
              _FakeTopic_0(this, Invocation.method(#insertTopic, [title])),
            ),
          )
          as _i7.Future<_i2.Topic>);

  @override
  _i7.Future<List<_i2.Topic>> getTopics() =>
      (super.noSuchMethod(
            Invocation.method(#getTopics, []),
            returnValue: _i7.Future<List<_i2.Topic>>.value(<_i2.Topic>[]),
          )
          as _i7.Future<List<_i2.Topic>>);

  @override
  _i7.Future<List<_i8.TopicWithStats>> getTopicsWithStats() =>
      (super.noSuchMethod(
            Invocation.method(#getTopicsWithStats, []),
            returnValue: _i7.Future<List<_i8.TopicWithStats>>.value(
              <_i8.TopicWithStats>[],
            ),
          )
          as _i7.Future<List<_i8.TopicWithStats>>);

  @override
  _i7.Future<_i2.Topic?> getTopicById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTopicById, [id]),
            returnValue: _i7.Future<_i2.Topic?>.value(),
          )
          as _i7.Future<_i2.Topic?>);

  @override
  _i7.Future<void> updateTopic(_i2.Topic? topic) =>
      (super.noSuchMethod(
            Invocation.method(#updateTopic, [topic]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteTopic(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTopic, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> togglePin(int? id, {required bool? isPinned}) =>
      (super.noSuchMethod(
            Invocation.method(#togglePin, [id], {#isPinned: isPinned}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i3.Entry> insertEntry({
    required int? topicId,
    required String? content,
    DateTime? createdAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertEntry, [], {
              #topicId: topicId,
              #content: content,
              #createdAt: createdAt,
            }),
            returnValue: _i7.Future<_i3.Entry>.value(
              _FakeEntry_1(
                this,
                Invocation.method(#insertEntry, [], {
                  #topicId: topicId,
                  #content: content,
                  #createdAt: createdAt,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.Entry>);

  @override
  _i7.Future<List<_i3.Entry>> getEntries(int? topicId) =>
      (super.noSuchMethod(
            Invocation.method(#getEntries, [topicId]),
            returnValue: _i7.Future<List<_i3.Entry>>.value(<_i3.Entry>[]),
          )
          as _i7.Future<List<_i3.Entry>>);

  @override
  _i7.Future<List<_i9.EntryWithAttachment>> getEntriesWithAttachments(
    int? topicId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEntriesWithAttachments, [topicId]),
            returnValue: _i7.Future<List<_i9.EntryWithAttachment>>.value(
              <_i9.EntryWithAttachment>[],
            ),
          )
          as _i7.Future<List<_i9.EntryWithAttachment>>);

  @override
  _i7.Future<void> updateEntry(_i3.Entry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#updateEntry, [entry]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteEntry(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEntry, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i4.EntryAttachment> insertEntryAttachment({
    required int? entryId,
    required String? filePath,
    String? mediaType = 'image',
    String? fileName,
    int? fileSize,
    String? mimeType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertEntryAttachment, [], {
              #entryId: entryId,
              #filePath: filePath,
              #mediaType: mediaType,
              #fileName: fileName,
              #fileSize: fileSize,
              #mimeType: mimeType,
            }),
            returnValue: _i7.Future<_i4.EntryAttachment>.value(
              _FakeEntryAttachment_2(
                this,
                Invocation.method(#insertEntryAttachment, [], {
                  #entryId: entryId,
                  #filePath: filePath,
                  #mediaType: mediaType,
                  #fileName: fileName,
                  #fileSize: fileSize,
                  #mimeType: mimeType,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.EntryAttachment>);

  @override
  _i7.Future<List<_i4.EntryAttachment>> getEntryAttachments(int? entryId) =>
      (super.noSuchMethod(
            Invocation.method(#getEntryAttachments, [entryId]),
            returnValue: _i7.Future<List<_i4.EntryAttachment>>.value(
              <_i4.EntryAttachment>[],
            ),
          )
          as _i7.Future<List<_i4.EntryAttachment>>);

  @override
  _i7.Future<void> deleteEntryAttachments(int? entryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEntryAttachments, [entryId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.LinkPreview?> getLinkPreview(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#getLinkPreview, [url]),
            returnValue: _i7.Future<_i5.LinkPreview?>.value(),
          )
          as _i7.Future<_i5.LinkPreview?>);

  @override
  _i7.Future<_i5.LinkPreview> insertLinkPreview({
    required String? url,
    String? title,
    String? description,
    String? imageUrl,
    String? imagePath,
    String? siteName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertLinkPreview, [], {
              #url: url,
              #title: title,
              #description: description,
              #imageUrl: imageUrl,
              #imagePath: imagePath,
              #siteName: siteName,
            }),
            returnValue: _i7.Future<_i5.LinkPreview>.value(
              _FakeLinkPreview_3(
                this,
                Invocation.method(#insertLinkPreview, [], {
                  #url: url,
                  #title: title,
                  #description: description,
                  #imageUrl: imageUrl,
                  #imagePath: imagePath,
                  #siteName: siteName,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.LinkPreview>);

  @override
  _i7.Future<void> deleteLinkPreview(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLinkPreview, [url]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i10.SearchResult>> searchEntries(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchEntries, [query]),
            returnValue: _i7.Future<List<_i10.SearchResult>>.value(
              <_i10.SearchResult>[],
            ),
          )
          as _i7.Future<List<_i10.SearchResult>>);
}

/// A class which mocks [FileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileService extends _i1.Mock implements _i11.FileService {
  MockFileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String> saveFile(String? sourcePath, {String? fileName}) =>
      (super.noSuchMethod(
            Invocation.method(#saveFile, [sourcePath], {#fileName: fileName}),
            returnValue: _i7.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(
                  #saveFile,
                  [sourcePath],
                  {#fileName: fileName},
                ),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<void> deleteFile(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFile, [path]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<int> getFileSize(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getFileSize, [path]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);
}
